spring:
  devtools:
    add-properties: false
  application:
    name: "bank"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    config:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


