spring:
  profiles:
    active: local
  devtools:
    add-properties: false
  application:
    name: BANK-SERVICE
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/fin_user
    username: root
    password: root
  cloud:
    config:
      enabled: false


server:
  port: 9010

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true


  tracing:
    sampling:
      probability: 1.0